class AppConstants {
  static const Map<String, String> cities = {
    'TOUT': 'Toutes les villes',
    'DAKAR': 'Dakar',
    'THIES': 'Thiès',
    'MBOUR': 'Mbour',
    'SALY': 'Saly',
    'TOUBA': 'Touba',
    'RUFISQUE': 'Rufisque',
    'SAINT_LOUIS': 'Saint-Louis',
    'ZIGUINCHOR': 'Ziguinchor',
    'DIOURBEL': 'Diourbel',
    'LOUGA': 'Louga',
    'FATICK': 'Fatick',
    'KAOLACK': 'Kaolack',
    'KOLDA': 'Kolda',
    'TAMBACOUNDA': 'Tambacounda',
    'MATAM': 'Matam',
    'KAFFRINE': 'Kaffrine',
    'KEDOUGOU': 'Kédougou',
    'SEDHIOU': 'Sédhiou',
    'SINE_SALOUM': 'Sine Saloum',
  };

  static const Map<String, String> propertyTypes = {
    'TOUT': 'Tous les types',
    'APARTMENT': 'Appartement',
    'APARTMENT_F3': 'Appartement F3',
    'APARTMENT_F4': 'Appartement F4',
    'APARTMENT_F5': 'Appartement F5',
    'CHAMBRE_SDB_INTERNE': 'Chambre SDB interne',
    'CHAMBRE_SIMPLE': 'Chambre simple',
    'COLOCATION': 'Colocation',
    'STUDIO': 'Studio',
    'MINI_STUDIO': 'Mini studio',
    'STUDIO_SEPARE': 'Studio séparé',
    'STUDIO_ENTREE_SALON': 'Studio entrée salon',
    'STUDIO_AMERICAIN': 'Studio américain',
    'MINI_STUDIO_AMERICAIN': 'Mini studio américain',
    'MAISON': 'Maison',
    'VILLA': 'Villa',
    'DUPLEX': 'Duplex',
    'TRIPLEX': 'Triplex',
    'IMMEUBLE': 'Immeuble',
    'TERRAIN': 'Terrain',
    'COMMERCIAL': 'Local Commercial',
    'BOUTIQUE': 'Boutique',
    'MAGASIN': 'Magasin',
    'BUREAU': 'Bureau',
    'SHOWROOM': 'Showroom',
    'USAGE_PRO': 'Usage professionnel',
    'VERGER': 'Verger',
    'CHAMPS': 'Champs',
    'DOMAINE': 'Domaine',
    'RANGE': 'Range',
    'HOTEL': 'Hôtel',
  };

  static const Map<String, String> listingCategories = {
    'TOUT': 'Toutes catégories',
    'RENT': 'Location',
    'SALE': 'Vente',
    'FURNISHED': 'Meublée (Vacances)',
  };

  static const List<String> neighborhoods = [
    "Tous les quartiers",
    "Almadies", "Almadies 2", "Amitié", "Avenue Bourguiba", "Bambelor", "Bambey", "Bargny", "Bayakh", "Bel air", 
    "Ben Taly", "Biscuiterie", "Bopp", "Cambérène", "Castor", "Centenaire", "Cité asecna", "Cité assemblée", 
    "Cité avion", "Cité Batrain", "Cité biagui", "Cité Check Amar", "Cité Damel", "Cité keur gorgui", 
    "Cité littoral", "Cité Mbakiyou Faye", "Cité mixta", "CITE MOURTADA", "Colobane", "Comico", "Dalifort", 
    "Derkle", "Diamaguene", "Diamalaye", "Diamniadio", "Diaxay", "Diass", "Diender", "Dieuppeul", 
    "Diofior", "Djidah thiaroye kaw", "Djilor", "Djily mbaye", "Fandene", "Fann", "Fann hock", "Fass", 
    "Fass Kaolack", "Fenêtre Mermoz", "Fissel", "Foire", "Foundiougne", "Gadaye", "Gandigal", "Gandiaye", 
    "Gibraltar", "Golf", "Gorée", "Gorom", "Gossas", "Grand mbao", "Grand yoff", "Grand-Dakar", 
    "Guediawaye", "Guereo", "Gueule-tapée", "Guinaw rail", "Guinguineo", "Hann", "Hann bel air", 
    "Hann marinas", "Hann mariste", "HLM", "HLM GRAND MEDINE", "HLM grand yoff", "Joal fadiouth", 
    "Kahone", "Kaolack", "Karack", "Karrang poste", "Kayar", "Keur madiabel", "Keur massar", "Keur Moussa", 
    "Keur Ndiaye lo", "Khar yalla", "Khombole", "Kounoune", "Lac rose", "Liberté 1", "Liberté 2", 
    "Liberté 3", "Liberté 4", "Liberté 5", "Liberté 6", "Liberté 6 extension", "Malibounda", "Malibu", 
    "Malika", "Mamelles", "Mariste", "Mariste 2", "Mbacke", "Mbao", "Mboss", "Mbodiene", "Mboro", 
    "Meckhe", "Medina", "Mermoz", "Mermoz-Sacré Coeur", "Monument renaissance", "Ndayane", "Ndiakhirate", 
    "Ndiagniao", "Ndoffane", "Ngaparou", "Ngor", "Ngoundiane", "Nguekhokh", "Ngueniene", "Nguering", 
    "Niague", "Niakoul rap", "Nianing", "Niary taly", "Nioro du rip", "Noflaye", "Nord foire", "Noto", 
    "OUAKAM MONPRIX", "Ouakam", "Ouakam brioche dorée", "Oukam Corniche", "Ouagou niaye", "Ouest foire", 
    "Parcelles assainies", "Passi", "Patte d'oie", "Pikine", "Plateau", "Point E", "Pointe sarene", 
    "Popenguine", "Pout", "Rufisque", "Sacré cœur 1", "Sacré cœur 2", "Sacré cœur 3", "Saly portudal", 
    "Sandiara", "Sangalkam", "Scat urbam", "Sebikotane", "Sendou", "Sessene", "Sibassor", "Sicap baobab", 
    "Sicap foire", "Sicap liberté", "Sicap mbao", "Sicap sacré cœur", "Sindia", "Sipres", "Sokone", 
    "Somone", "Soum", "Sud foire", "Tassette", "Thiadiaye", "Thiaroye", "Thienaba", "Thongor", 
    "Tivaouane peulh", "Tivaouane thies", "Touba toul", "Toubacouta", "Toubab dialo", "VDN", "Virage", 
    "Warang", "Yene", "Yeumbeul", "Yoff", "Zac mbao", "Zone A", "Zone B", "Zone de captage", "Zone industrielle"
  ];
}
