# Generated by Django 6.0.3 on 2026-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nils_profile',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='nils_profile',
            name='nils_number',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
