# Generated by Django 6.0.3 on 2026-03-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified_pro',
            field=models.BooleanField(default=False, verbose_name='Professionnel Vérifié (Badge)'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('AGENCY', 'Agence Immobilière'), ('BROKER', 'Courtier'), ('AGENT', 'Agent')], default='TENANT', max_length=20, verbose_name='Statut du compte'),
        ),
    ]
