# Generated by Django 6.0.3 on 2026-03-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_pro_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'agence ou de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='coverage_area',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zone de couverture'),
        ),
    ]
