# Generated by Django 6.0.3 on 2026-03-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_company_name_user_coverage_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Photo de profil ou Logo'),
        ),
    ]
