# Generated by Django 6.0.3 on 2026-03-26 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='nils_profile',
            name='nils_type',
            field=models.CharField(choices=[('TENANT', 'Locataire'), ('LANDLORD', 'Bailleur'), ('AGENCY', 'Agence Immobilière'), ('BROKER', 'Courtier'), ('AGENT', 'Agent')], default='TENANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='nils_profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nils_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
