# Generated by Django 6.0.3 on 2026-03-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_nils_profile_nils_type_alter_nils_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='Téléphone vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Code OTP'),
        ),
    ]
