# Generated by Django 6.0.3 on 2026-04-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_phone_verified_user_phone_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cni_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNI / Passeport'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Employeur / Titre d'emploi"),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Statut matrimonial'),
        ),
        migrations.AddField(
            model_name='user',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'épouse/époux"),
        ),
    ]
