# Generated by Django 5.1.6 on 2026-04-08 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_document_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_solvable',
            field=models.BooleanField(default=False, verbose_name='Locataire Solvable (Badge)'),
        ),
        migrations.CreateModel(
            name='SolvencyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('PAYSLIP', 'Bulletin de Salaire'), ('CONTRACT', 'Contrat de Travail'), ('BANK_STATEMENT', 'Relevé Bancaire'), ('NINEA', 'NINEA (Auto-entrepreneur)'), ('ADMIN_DOC', 'Document Administratif')], max_length=50)),
                ('file', models.FileField(upload_to='solvency_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solvency_docs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
