# Generated by Django 5.1.6 on 2026-04-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_user_referred_by_pointtransaction_userpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
    ]
