# Generated by Django 5.1.6 on 2026-04-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Site Internet / Portfolio'),
        ),
    ]
