# Generated by Django 5.1.6 on 2026-04-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_phone_verified',
            field=models.BooleanField(default=True, verbose_name='Téléphone vérifié'),
        ),
    ]
