# Generated by Django 6.0.3 on 2026-04-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la publicité')),
                ('ad_type', models.CharField(choices=[('BANNER', 'Bannière Image'), ('SCRIPT', 'Code Script (Google Ads, etc)')], default='BANNER', max_length=10)),
                ('location', models.CharField(choices=[('TOP', 'Haut de page'), ('BOTTOM', 'Bas de page'), ('BETWEEN_LISTINGS', 'Entre les annonces (In-Feed)'), ('POPUP', 'Pop-up promotionnel'), ('SIDEBAR', 'Barre latérale (Sidebar)')], default='TOP', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/banners/', verbose_name='Image de la bannière')),
                ('target_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien de redirection')),
                ('script_content', models.TextField(blank=True, null=True, verbose_name='Code Script / HTML')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publicité active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
            },
        ),
    ]
