# Generated by Django 6.0.3 on 2026-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_txt_content', models.TextField(blank=True, help_text="Collez ici les lignes fournies par Google AdSense ou d'autres régies.", verbose_name='Contenu du fichier ads.txt')),
            ],
            options={
                'verbose_name': 'Configuration AdSense (ads.txt)',
                'verbose_name_plural': 'Configuration AdSense (ads.txt)',
            },
        ),
    ]
