# Generated by Django 5.1.6 on 2026-04-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_adsconfig_id_alter_advertisement_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('TOP', 'Haut de page (Banner)'), ('BOTTOM', 'Bas de page (Banner)'), ('BETWEEN_LISTINGS', 'Entre les annonces (In-Feed)'), ('POPUP', 'Pop-up (Surcouche)'), ('POPUNDER', 'Pop-under (Arrière-plan)'), ('SIDEBAR', 'Barre latérale (Sidebar)')], default='TOP', max_length=20),
        ),
    ]
