# Generated by Django 5.1.6 on 2026-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_alter_advertisement_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(choices=[('TOP', 'Haut de page (Banner)'), ('BOTTOM', 'Bas de page (Banner)'), ('BETWEEN_LISTINGS', 'Entre les annonces (In-Feed)'), ('POPUP', 'Pop-up (Surcouche)'), ('POPUNDER', 'Pop-under (Arrière-plan)'), ('SIDEBAR', 'Barre latérale (Sidebar)'), ('LEFT_SKIN', 'Habillage Gauche (PC uniquement)'), ('RIGHT_SKIN', 'Habillage Droit (PC uniquement)')], default='TOP', max_length=20),
        ),
    ]
