# Generated by Django 5.1.6 on 2026-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_advertisement_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='NohanSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name="Activer l'assistant Nohan")),
            ],
            options={
                'verbose_name': 'Paramètres Nohan',
                'verbose_name_plural': 'Paramètres Nohan',
            },
        ),
    ]
