# Generated by Django 6.0.3 on 2026-03-16 23:42

import solvable.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('IN_MEDIATION', 'In Mediation'), ('RESOLVED', 'Resolved'), ('IMPACTED', 'Impacted on NILS')], default='IN_MEDIATION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mediation_end_date', models.DateTimeField(default=solvable.models.default_mediation_end)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('LATE', 'Late'), ('UNPAID', 'Unpaid'), ('REPORTED', 'Reported')], default='PAID', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalFiliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
