# Generated by Django 6.0.3 on 2026-03-16 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logersn', '0002_initial'),
        ('solvable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reported_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_against_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalfiliation',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_filiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentalfiliation',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filiations', to='logersn.property'),
        ),
        migrations.AddField(
            model_name='rentalfiliation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_filiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='rental_filiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='solvable.rentalfiliation'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='rental_filiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='solvable.rentalfiliation'),
        ),
    ]
