# Generated by Django 6.0.3 on 2026-03-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('UNPAID_RENT', 'Loyer impayé'), ('LATE_PAYMENT', 'Retard de paiement'), ('PROPERTY_DAMAGE', 'Dégradation du bien'), ('BAD_BEHAVIOR', 'Mauvais comportement / Conflit'), ('OTHER', 'Autre')], default='UNPAID_RENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seulement pour les loyers impayés ou dégradations', max_digits=12, null=True),
        ),
    ]
