# Generated by Django 6.0.3 on 2026-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0003_incidentreport_incident_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire (Optionnel)'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='Preuve de paiement (Optionnel)'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='month_year',
            field=models.DateField(verbose_name='Mois et Année du Loyer (1er du mois)'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(choices=[('PAID', 'Payé à temps'), ('LATE', 'Payé en retard'), ('UNPAID', 'Impayé')], default='PAID', max_length=20),
        ),
    ]
