# Generated by Django 6.0.3 on 2026-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0004_paymenthistory_created_at_paymenthistory_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='contestation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de contestation'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='is_contested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='contestation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motif de contestation'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='is_contested',
            field=models.BooleanField(default=False),
        ),
    ]
