# Generated by Django 6.0.3 on 2026-03-26 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0006_alter_property_bedrooms_alter_property_has_garage_and_more'),
        ('solvable', '0005_incidentreport_contestation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalfiliation',
            name='rating_for_landlord',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note du locataire pour le bailleur'),
        ),
        migrations.AddField(
            model_name='rentalfiliation',
            name='rating_for_tenant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Note du bailleur pour le locataire'),
        ),
        migrations.AlterField(
            model_name='rentalfiliation',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', "En attente d'approbation"), ('ACTIVE', 'Actif'), ('TERMINATION_REQUESTED', 'Résiliation demandée'), ('TERMINATED', 'Terminé')], default='PENDING_APPROVAL', max_length=50),
        ),
        migrations.CreateModel(
            name='PropertyApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message au bailleur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('INTERESTED', 'Intéressé (à visiter)'), ('REJECTED', 'Refusé'), ('ACCEPTED', 'Accepté pour location')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_applications', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='logersn.property')),
            ],
        ),
    ]
