# Generated by Django 6.0.3 on 2026-04-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0006_rentalfiliation_rating_for_landlord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='incident_type',
            field=models.CharField(choices=[('UNPAID_RENT', 'Loyer impayé'), ('UNPAID_COMMISSION', 'Commission impayée (Courtage)'), ('LATE_PAYMENT', 'Retard de paiement'), ('PROPERTY_DAMAGE', 'Dégradation du bien'), ('BAD_BEHAVIOR', 'Mauvais comportement / Conflit'), ('OTHER', 'Autre')], default='UNPAID_RENT', max_length=50),
        ),
    ]
