# Generated by Django 5.1.6 on 2026-04-08 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0009_incidentreport_beneficiary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='notifier_role',
            field=models.CharField(choices=[('SELF', 'Pour moi-même (Propriétaire / Bailleur)'), ('INTERMEDIARY', "Pour le compte d'un client tiers (Mandat)")], default='SELF', max_length=20, verbose_name='Rôle du déclarant'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='property_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse du bien concerné (si pas via contrat app)'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la personne signalée'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reported_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Téléphone de la personne signalée (si pas encore sur l'app)"),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='rental_filiation',
            field=models.ForeignKey(blank=True, help_text="Optionnel si pas de contrat direct dans l'app", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='solvable.rentalfiliation'),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='reported_tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents_against_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfessionalFraudReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_pro_name', models.CharField(max_length=255, verbose_name='Nom du Professionnel / Agence')),
                ('reported_pro_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone (si connu)')),
                ('reported_pro_email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Email (si connu)')),
                ('fraud_description', models.TextField(verbose_name='Détails de la fraude ou dette')),
                ('proof_file', models.FileField(upload_to='pro_fraud_proofs/', verbose_name='Preuve (Reçu, Photo, Screenshot)')),
                ('is_validated', models.BooleanField(default=False, verbose_name='Validé par DigitalH Admin')),
                ('is_critical_alert', models.BooleanField(default=False, verbose_name='Afficher en Alerte Critique (Bande défilante)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against_me_pro', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur inscrit (si match trouvé)')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signalement de Fraude Pro',
                'verbose_name_plural': 'Signalements de Fraude Pro',
            },
        ),
    ]
