# Generated by Django 5.1.6 on 2026-04-23 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solvable', '0012_systemalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seulement pour les loyers impayés ou dégradations', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='platformpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Prix (FCFA)'),
        ),
        migrations.AlterField(
            model_name='rentalfiliation',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlord_filiations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalfiliation',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='rentalfiliation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_filiations', to=settings.AUTH_USER_MODEL),
        ),
    ]
