# Generated by Django 5.1.6 on 2026-04-28 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0024_property_is_on_promotion_property_promo_description_and_more'),
        ('solvable', '0013_alter_incidentreport_amount_due_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name="Date d'arrivée")),
                ('end_date', models.DateField(verbose_name='Date de départ')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='logersn.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVisitRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField(verbose_name='Date souhaitée')),
                ('preferred_time', models.TimeField(verbose_name='Heure souhaitée')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SCHEDULED', 'Planifiée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_requests', to='logersn.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
