# Generated by Django 6.0.3 on 2026-03-16 23:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('STUDIO', 'Studio'), ('COMMERCIAL', 'Commercial')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(max_length=100)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.FileField(upload_to='properties/')),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
    ]
