# Generated by Django 6.0.3 on 2026-03-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0004_alter_property_city_alter_property_neighborhood_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=0, verbose_name='Nombre de chambres'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(default=False, verbose_name='Garage disponible'),
        ),
        migrations.AddField(
            model_name='property',
            name='surface',
            field=models.IntegerField(default=0, verbose_name='Surface (m2)'),
        ),
        migrations.AddField(
            model_name='property',
            name='toilets',
            field=models.IntegerField(default=0, verbose_name='Nombre de toilettes'),
        ),
        migrations.AddField(
            model_name='property',
            name='total_rooms',
            field=models.IntegerField(default=1, verbose_name='Nombre total de pièces'),
        ),
    ]
