# Generated by Django 6.0.3 on 2026-03-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0005_property_bedrooms_property_has_garage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de chambres'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_garage',
            field=models.BooleanField(blank=True, default=False, verbose_name='Garage disponible'),
        ),
        migrations.AlterField(
            model_name='property',
            name='surface',
            field=models.IntegerField(blank=True, default=0, verbose_name='Surface (m2)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='toilets',
            field=models.IntegerField(blank=True, default=0, verbose_name='Nombre de toilettes'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_rooms',
            field=models.IntegerField(blank=True, default=1, verbose_name='Nombre total de pièces'),
        ),
    ]
