# Generated by Django 6.0.3 on 2026-04-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0007_property_air_conditioning_property_generator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Nombre de clics d'action"),
        ),
        migrations.AddField(
            model_name='property',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues'),
        ),
    ]
