# Generated by Django 6.0.3 on 2026-04-06 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0008_property_clicks_count_property_views_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Prix Publication')),
                ('boost_daily_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Prix Boost par jour')),
                ('popup_daily_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Prix Pop-up par jour')),
            ],
            options={
                'verbose_name': 'Paramètres des Tarifs',
                'verbose_name_plural': 'Paramètres des Tarifs (DigitalH)',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='boost_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Boost valide jusqu'au"),
        ),
        migrations.AddField(
            model_name='property',
            name='is_boosted',
            field=models.BooleanField(default=False, verbose_name='Annonce Boostée'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured_popup',
            field=models.BooleanField(default=False, verbose_name='Mise en avant Pop-up'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Frais de publication payés'),
        ),
        migrations.AddField(
            model_name='property',
            name='popup_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Pop-up valide jusqu'au"),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('PUBLICATION', 'Frais de publication (100F)'), ('BOOST', 'Boost Annonce (100F/j)'), ('POPUP', 'Mise en avant Pop-up (500F/j)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence FedaPay / Interne')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussite'), ('FAILED', 'Échec')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='logersn.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions (Comptabilité)',
            },
        ),
    ]
