# Generated by Django 5.1.6 on 2026-04-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0018_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, choices=[('BAIL', 'BAIL'), ('TITRE_FONCIER_INDIVIDUEL', 'TITRE FONCIER INDIVIDUEL'), ('TITRE_FONCIER_GLOBAL', 'TITRE FONCIER GLOBAL'), ('ACTE_DE_VENTE', 'ACTE DE VENTE'), ('DELIBERATION', 'DELIBERATION')], max_length=50, null=True, verbose_name='Type de document'),
        ),
        migrations.AddField(
            model_name='property',
            name='internal_ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence Interne (Pro)'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='En ligne'),
        ),
        migrations.AddField(
            model_name='property',
            name='private_contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Infos Contact Privé (Pro)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='boost_daily_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Prix Boost par jour'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='popup_daily_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20, verbose_name='Prix Pop-up par jour'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_furnished',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=20, verbose_name='Prix Publication (Meublé)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_rent',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Prix Publication (Location)'),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='publication_fee_sale',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=20, verbose_name='Prix Publication (Vente)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Prix (CFA)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Prix par nuitée (Meublé)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
