# Generated by Django 5.1.6 on 2026-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0019_property_document_type_property_internal_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien Vidéo (YouTube ou TikTok)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(max_length=100),
        ),
    ]
