# Generated by Django 5.1.6 on 2026-04-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0020_property_video_url_alter_property_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='boosted_views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de vues (Boost)'),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_level',
            field=models.IntegerField(blank=True, default=0, verbose_name="Niveau d'étage"),
        ),
        migrations.AddField(
            model_name='property',
            name='has_concierge',
            field=models.BooleanField(default=False, verbose_name='Service de conciergerie'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Ascenseur'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_security',
            field=models.BooleanField(default=False, verbose_name='Sécurité 24/7'),
        ),
    ]
