# Generated by Django 5.1.6 on 2026-04-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0021_property_boosted_views_count_property_floor_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name="Note de l'administrateur (Sera envoyée au propriétaire)"),
        ),
    ]
