# Generated by Django 5.1.6 on 2026-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0022_property_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='boost_slider_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=20, verbose_name='Prix Boost Slider par jour'),
        ),
        migrations.AddField(
            model_name='property',
            name='boost_status',
            field=models.CharField(choices=[('NONE', 'Aucun'), ('PENDING', 'En attente de validation'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='popup_status',
            field=models.CharField(choices=[('NONE', 'Aucun'), ('PENDING', 'En attente de validation'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='boost_type',
            field=models.CharField(choices=[('NONE', 'Aucun'), ('FEED', 'In-Feed (Liste)'), ('SLIDER', 'Slider (Accueil)'), ('POPUP', 'Pop-up Premium')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='boost_daily_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20, verbose_name='Prix Boost In-Feed par jour'),
        ),
    ]
