# Generated by Django 5.1.6 on 2026-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0023_pricingconfig_boost_slider_fee_property_boost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_on_promotion',
            field=models.BooleanField(default=False, verbose_name='Afficher en promotion'),
        ),
        migrations.AddField(
            model_name='property',
            name='promo_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texte de promotion (ex: -10% ce weekend)'),
        ),
        migrations.AddField(
            model_name='property',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Prix Promotionnel (CFA)'),
        ),
    ]
