# Generated by Django 6.0.4 on 2026-05-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logersn', '0025_nohanmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Appartement'), ('APARTMENT_F3', 'Appartement F3'), ('APARTMENT_F4', 'Appartement F4'), ('APARTMENT_F5', 'Appartement F5'), ('CHAMBRE_SDB_INTERNE', 'Chambre salle de bain interne'), ('CHAMBRE_SIMPLE', 'Chambre simple'), ('COLOCATION', 'Colocation'), ('STUDIO', 'Studio'), ('MINI_STUDIO', 'Mini studio'), ('STUDIO_SEPARE', 'Studio séparé'), ('STUDIO_ENTREE_SALON', 'Studio entrée salon'), ('STUDIO_AMERICAIN', 'Studio américain'), ('MINI_STUDIO_AMERICAIN', 'Mini studio américain'), ('MAISON', 'Maison'), ('VILLA', 'Villa'), ('DUPLEX', 'Duplex'), ('TRIPLEX', 'Triplex'), ('IMMEUBLE', 'Immeuble'), ('TERRAIN', 'Terrain'), ('COMMERCIAL', 'Local Commercial'), ('BOUTIQUE', 'Boutique'), ('MAGASIN', 'Magasin'), ('BUREAU', 'Bureau'), ('SHOWROOM', 'Showroom'), ('USAGE_PRO', 'Usage professionnel'), ('VERGER', 'Verger'), ('CHAMPS', 'Champs'), ('DOMAINE', 'Domaine'), ('RANGE', 'Range'), ('HOTEL', 'Hôtel')], max_length=50),
        ),
    ]
